課題7（ログイン機能追加）
obake-fe/bulletin-board pull request #15
Opened 2022-05-10 16:42 UTC by obake-fe

## 課題7（ログイン機能追加）
ログイン機能を実装して、投稿者名の入力は不要にしてください

2022-05-18 05:29 UTC, naoyukik commented
@obake-fe 
新しいライブラリーを入れたりという大きな変更が入る場合、その処理だけでPRを出すとスムーズです。
そうしないと、ライブラリーが行った変更なのか開発者が行った変更なのかが曖昧になるので、結局のところレビューが機能しなくなります。

また、コミット単位のレビューっていうのはかなり非効率です。
コミット単位となると、あるコミットで指摘したところがあとのコミットで修正されている可能性があり、それをいちいち確認しているのはレビュアーの時間をかなり割くことになります。

2022-06-22 13:15 UTC, naoyukik commented on src/tests/Feature/ThreadControllerTest.php
> +        $this->actingAs($user)->post('/', [
テスト内で同一のログインユーザーを使用できるのであれば、変数に格納しちゃってください。

2022-07-17 06:53 UTC, obake-fe commented on src/tests/Feature/ThreadControllerTest.php
> +        $this->actingAs($user)->post('/', [
こちらで修正しました！
https://github.com/obake-fe/bulletin-board/pull/15/commits/9889409e74206aa8a3e08e9e648c34d4f70c30ba

2022-07-22 12:26 UTC, naoyukik requested changes

2022-07-22 12:26 UTC, naoyukik commented on src/app/Http/Middleware/VerifyCsrfToken.php
> +        {
括弧の位置が違うようです

2022-07-24 08:08 UTC, obake-fe commented on src/app/Http/Middleware/VerifyCsrfToken.php
> +        {
@naoyukik 
こちらで修正しました🙇‍♂️
https://github.com/obake-fe/bulletin-board/pull/15/commits/ca9d928ab1b1ee7fe1fde3bcf66b60f776cba873

2022-08-25 05:53 UTC, naoyukik approved these changes
マジ遅くてごめんなさい LGTM 👍

2022-08-25 16:16 UTC, merged